# Generated by Django 4.1.8 on 2023-06-25 14:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="narration",
            options={"ordering": ["book", "pk"]},
        ),
    ]
