# Generated by Django 4.1.8 on 2023-06-26 08:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0003_recordingrequest_recording"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recordingrequest",
            name="status",
            field=models.IntegerField(choices=[(1, "New"), (2, "Started"), (3, "Finished")], default=1),
        ),
    ]
