# Generated by Django 4.1.8 on 2023-07-25 10:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0005_book_cover_book_public_book_thumbnail"),
    ]

    operations = [
        migrations.AddField(
            model_name="recording",
            name="recording_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
