# Generated by Django 4.1.8 on 2023-07-25 10:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0006_recording_recording_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recording",
            old_name="recording_name",
            new_name="narrator_name",
        ),
    ]
