# Generated by Django 4.1.8 on 2023-07-27 13:26

import books.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0008_alter_narration_audio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recording",
            name="audio",
            field=models.FileField(upload_to=books.models.upload_location),
        ),
    ]
