# Generated by Django 4.1.8 on 2023-09-16 14:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0009_alter_recording_audio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="image",
            field=models.FileField(upload_to=""),
        ),
    ]
