# Generated by Django 4.1.8 on 2023-09-19 07:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0011_alter_page_image_combinednarrations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="image",
            field=models.FileField(upload_to=""),
        ),
    ]
