# Generated by Django 4.1.8 on 2023-09-19 17:03

import books.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("books", "0014_alter_combinednarrations_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="combinednarrations",
            name="finalVideo",
            field=models.FileField(upload_to=books.models.upload_video),
        ),
        migrations.CreateModel(
            name="Narrator",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("narratorName", models.CharField(max_length=200)),
                (
                    "book",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="narrator",
                        to="books.book",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="narrator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CombineVideo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("pages", models.FileField(upload_to=books.models.upload_video)),
                ("audio", models.FileField(upload_to=books.models.upload_location)),
                (
                    "book",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comvideo",
                        to="books.book",
                    ),
                ),
                (
                    "narrator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="comvideo", to="books.narrator"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comvideo",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="combinednarrations",
            name="narratorName",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="combined", to="books.narrator"
            ),
        ),
    ]
