# Generated by Django 4.1.8 on 2023-09-20 08:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0016_remove_combinednarrations_finalvideo"),
    ]

    operations = [
        migrations.AddField(
            model_name="combinednarrations",
            name="finalVideo",
            field=models.FileField(default=django.utils.timezone.now, upload_to="upload_video"),
            preserve_default=False,
        ),
    ]
